server:
  port: 8081

spring:
  datasource:
    url: ${DEV_URL:jdbc}
    username: ${DEV_USER}
    password: ${DEV_PASSWORD}
    driver-class-name: ${DEV_DRIVER_NAME}
  jpa:
    show-sql: ${DEV_SHOW_SQL}
    hibernate:
      ddl-auto: ${DEV_HIBERNATE_DDL_AUTO}
